/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.io.IOException;
// import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, IOException {
        // TestCases tests = new TestCases(); // Initialize your test class
        // Amazonlink amaz = new Amazonlink();
        // BMSHyperlinkCount hcount = new BMSHyperlinkCount();
        Lnkedinpost pst = new Lnkedinpost();
        //  Nestedframe ns = new Nestedframe();
        // IMDBratings rt = new IMDBratings();
        // WindowHandle wh = new WindowHandle();
        // BMSImgurl imag = new BMSImgurl();
        // //TODO: call your test case functions one after other here

        // tests.testCase01();
        // amaz.searchAmazon();
        // hcount.HyperlinkCountBMS();
        pst.post();
        //  ns.nsframe();
        // rt.Rating();
        // wh.Whandle();
        // imag.imageurl();

        //END Tests
        // amaz.endTest();
        // hcount.endTest();
        pst.endTest();
        //  ns.endTest();
        // tests.endTest(); // End your test by clearning connections and closing browser
        // rt.endTest();
//         wh.endTest();
// imag.endTest();

    }

    public static void main(String[] args) throws InterruptedException, IOException {
        new App().getGreeting();
    }
}
